config/routes.rb
Rails.application.routes.draw do
  resources :card 
  get 'regulation/new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products , only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :likes,     only: [:create,:destroy]
    resources :comments,  only: [:new, :create]
    collection do
      get :sell
      get :select_category_m
      get :select_category_s
    end
    member do 
      get :showmain
      get :show_transaction_main
      get :show_completed_main
      get :purchase_transaction
      get :purchase_completed
      get :buy
      get :pay
      get :ship
      get :recieve
      get :pend
      get :resell
      get :close
    end

  end
  resources :users do
    member do
      get :plofile
      get :identification
      get :card
      get :logout
      get :notification
      get :todo
      get :like
      get :showedit
      get :show_transaction
      get :show_completed
      get :purchase
      get :purchased
    end
  end
  resources :trials, only: [:index,:create,:new, :edit, :update]
  resources :regulation do
    collection do
      get :singup1
      get :singup2
      get :singup3
      get :singup4
      get :singup5
    end
  end 
end  

app/models/trial.rb
class Trial < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  def index
    @trials = Trial.order('id DESC')
    @trial = Trial.new()
  end
  def new
    @trial = Trial.new()
  end
  def create
    @trial=Trial.new(trial_params)
    redirect_to "/trials"
  end

  def edit
    @trial=Trial.find(params[:id])
    @trial.image.cache!
  end
  def update
    binding.pry
    @trial=Trial.find(params[:id])
    @trial.update(trial_params)
    redirect_to "/trials"
  end
  private
  def trial_params
   params.require(:trial).permit(:image,:image_cache)
  end
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/trials/edit.html.haml
%span> Hello
,World
:css
  span{color:blue;}
= form_for @trial do |f|
  = f.file_field :image, class:"new-image"
  = f.hidden_field :image_cache, class:"image_cache"
  = f.submit "Send", class: "new__message__submit-btn"
.image_box_inner

:javascript
  //Display the image When a user select one
  $(function(){    
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          var html =`<img id="current_image_for_edit" src="${e.target.result}" hight="100px" width="100px" ></img>`;
          $(".image_box_inner").append(html);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }

    $(".new-image").on("change",function(e){
      e.preventDefault();
      $('#current_image_for_edit').remove();
      $('.dummy_post_box').remove();
      readURL(this);
    });
  })
  $(window).on('load', function(e) {
    e.preventDefault();
    $('#current_image_for_edit').remove();
    $('.dummy_post_box').remove();
    var img_file = $(".image_cache").val();
    var html =`<img id="current_image_for_edit" src="/tmp/${img_file}" hight="100px" width="100px" ></img>`;
      
  });

app/views/trials/index.html.haml
%span> Hello,World
%br/
This page is only for initial test to deploy.
%br/
= link_to new_trial_path, class:"link" do
  "To Updating Test of Image file"
%br/
:css
  span{color:blue;font-weight:bold; font-size:30px;}
  .link{
    background:lightblue;
  }

- @trials.each do |trial|
  - if trial.image.present?
    = link_to edit_trial_path(trial) do
      = image_tag trial.image.url ,class:"image_link",size: "200x200"
 

app/views/trials/new.html.haml
%span> Hello
,World
:css
  span{color:blue;}
= form_for @trial do |f|
  = f.file_field :image, class:"new-image"
  = f.hidden_field :image_cache, class:"image_cache"
  = f.submit "Send", class: "new__message__submit-btn"
.image_box_inner

:javascript
  //Display the image When a user select one
  $(function(){    
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          var html =`<img id="current_image_for_edit" src="${e.target.result}" hight="100px" width="100px" ></img>`;
          $(".image_box_inner").append(html);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $(".new-image").on("change",function(e){
      e.preventDefault();
      $('#current_image_for_edit').remove();
      $('.dummy_post_box').remove();
      readURL(this);
    });
  })