config/routes.rb
Rails.application.routes.draw do
  resources :card 
  get 'regulation/new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products , only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :likes,     only: [:create,:destroy]
    resources :comments,  only: [:new, :create]
    collection do
      get :sell
      get :select_category_m
      get :select_category_s
    end
    member do 
      get :showmain
      get :show_transaction_main
      get :show_completed_main
      get :purchase_transaction
      get :purchase_completed
      get :buy
      get :pay
      get :ship
      get :recieve
      get :pend
      get :resell
      get :close
    end

  end
  resources :users do
    member do
      get :plofile
      get :identification
      get :card
      get :logout
      get :notification
      get :todo
      get :like
      get :showedit
      get :show_transaction
      get :show_completed
      get :purchase
      get :purchased
    end
  end
  resources :trials, only: [:index,:create,:new, :edit, :update]
  resources :regulation do
    collection do
      get :singup1
      get :singup2
      get :singup3
      get :singup4
      get :singup5
    end
  end 
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :likes, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_one :address
  accepts_nested_attributes_for :address 
  has_many :cards
  has_one :pay
  accepts_nested_attributes_for :pay

  has_many :buyed_products,                                         foreign_key: "buyer_id", class_name: "Product"
  has_many :selling_products,  -> { where("buyer_id is NULL") },    foreign_key: "user_id", class_name: "Product"
  has_many :sold_products,     -> { where("buyer_id is not NULL")}, foreign_key: "user_id", class_name: "Product"
  
  # user情報入力バリデーション
    # 値が空ではない
      validates :nickname, :email, :password, :password_confirmation, :family_name, :first_name,
                :family_name_kana, :first_name_kana, :birthday_year, :birthday_month, :birthday_day, presence: true
      validates :password, confirmation: true
    # 苗字、名前は全角のカタ、ひら、漢字のどれかである
      validates :family_name, format:{ with: /\A[ぁ-んァ-ン一-龥]/ }
      validates :first_name, format:{ with: /\A[ぁ-んァ-ン一-龥]/ }
    # フリガナは全角カタカナである
      validates :family_name_kana, format:{ with: /\A[ァ-ヶー－]+\z/ }
      validates :first_name_kana, format:{ with: /\A[ァ-ヶー－]+\z/ }
    # 数値範囲指定  
      validates :birthday_year, numericality:{ greater_than_or_equal_to: 1930 }
      validates :birthday_year, numericality:{ less_than_or_equal_to: 2018 }
      validates :birthday_month, numericality:{greater_than_or_equal_to: 1 }
      validates :birthday_month, numericality:{less_than_or_equal_to: 12 }
      validates :birthday_day, numericality:{greater_than_or_equal_to: 1 }
      validates :birthday_day, numericality:{less_than_or_equal_to: 31 }     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def card
    @user = User.new() #temporaly 
  end
  def logout
  end
  
  def notification
    @notifications = [1] #nemporaly
  end
  
  def todo
    @todos = [1] #nemporaly
  end
  
  def like
    @likes = current_user.likes
    @state_pending = false;
    @likes.each do | like |
      if like.product.state == "pending"
        @state_pending = true;
      end
    end
  end
  def plofile
    #仮のモデル作成
    @user =User.new()
  end  
  def identification
    #仮のモデル作成
    @user =User.new()
  end 

  def showedit
    @products=current_user.selling_products.where(state: ['in_sales' ,'pending']).order("id DESC")
  end 
  def show_transaction
    @products=current_user.sold_products.where(state: ['waiting_for_shipping', 'on_delivery' ,'arrived']).order("id DESC")
  end
  def show_completed
    @products=current_user.sold_products.where(state: 'completed' ).order("id DESC")
  end

  def purchase
    @products=current_user.buyed_products.where(state: ['waiting_for_shipping', 'on_delivery', 'arrived']).order("id DESC")
  end
  def purchased
    @products=current_user.sold_products.where(state: 'completed' ).order("id DESC")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.haml
%section.user-credit-card
  %h2.user-credit-card__head
    支払い方法
  .user-credit-card__inner
    %section.user-credit-card__inner__content
      .user-credit-card__inner__content__title
        %h3.user-credit-card__inner__content__title__head クレジットカード一覧
      %ul.user-credit-card__inner__content__list
        %li.user-credit-card__inner__content__list__item
          = form_with(model: @user, local: true,class:"user-credit-card__inner__content__list__item__form" ) do |f|
            %figure.user-credit-card__inner__content__list__item__form__figure
              = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615", class:".user-credit-card__inner__content__list__item__form__figure__img", height:"18px"
            = f.hidden_field :__csrf_value, class:"user-credit-card__inner__content__list__item__form__hidden" , value: ""
            = f.hidden_field :card_sequence_no, value: "8Zc7efHfaa7CgTt15tfTv3cc", class:"user-credit-card__inner__content__list__item__form__hidden"
            .user-credit-card__inner__content__list__item__form__settings-payment-num
              ************7345
            .user-credit-card__inner__content__list__item__form__settings-payment-num
              09 / 20
            = f.hidden_field :method, value: "card", class:"user-credit-card__inner__content__list__item__form__hidden"
            = f.submit "削除する", class:"user-credit-card__inner__content__list__item__form__settings-payment-remove"            
    .user-credit-card__inner__settings-not-regist
      = link_to "", class:"user-credit-card__inner__settings-not-regist__remarks-link" do
        %span.user-credit-card__inner__settings-not-regist__remarks-link__text 支払い方法について
        = icon("fas", "angle-right icon-arrow-right fa-1g")

app/views/users/_plofile.html.haml
.content
  %section.chapter-container
    %h2.chapter-head プロフィール
    =form_with(model: @user) do |f| 
      .profile-icon
        %figure
          = image_tag"//static.mercdn.net/images/member_photo_noimage_thumb.png"
        =f.text_field :name,value:"ゆり" , class: "i"
      .profile-content
        =f.text_area :introduction, placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class: "d"
        %button.btn-red
          変更する

app/views/users/_purchase_main.html.haml
%section.mypage-tab-container
  %h2.mypage-tab-head 購入した商品
  %ul.listing-tabs
    %li.listing-tabs__tab.purchaselist.tab_purchase_transaction
      %h3
        = link_to   purchase_user_path(current_user), data:{toggle:"tab"} do
          取引中
    %li.listing-tabs__tab.purchaselist.tab_purchased_completed
      %h3
        = link_to   purchased_user_path(current_user),   data:{toggle:"tab"} do
          過去の取引
  .tab-content
    %ul.mypage-item
      - if @products.present?
        -@products.each do | product |
          %li
            .mypage-item__link
              - if product.state == "waiting_for_shipping" || product.state == "on_delivery" || product.state == "arrived" 
                = link_to purchase_transaction_product_path(product), class: "mypage-item__link__link"  do
                  .mypage-item__link__link__wrapper
                    .mypage-item__link__link__wrapper__main
                      .mypage-item__link__link__wrapper__main__figure
                        =image_tag product.product_images[0].image.url , class: "is-higher-width" 
                      .mypage-item-body
                        .mypage-item-text
                          = product.title
                        %div
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "heart")
                            %span
                              = product.likes.count
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "comment")
                            %span
                              = product.comments.count
                          - if product.state == "waiting_for_shipping"
                            .mypage-item-status.bold.blueblock
                              発送待ち
                          - elsif product.state == "on_delivery"
                            .mypage-item-status.bold.redblock
                              配達中
                          - elsif product.state == "arrived"
                            .mypage-item-status.bold.blueblock
                              出品者による完了処置中
                    .mypage-item__link__link__wrapper__icon
                      = icon("fas", "angle-right fa-2x")
              - elsif product.state == "completed"
                = link_to purchase_completed_product_path(product), class: "mypage-item__link__link"  do
                  .mypage-item__link__link__wrapper
                    .mypage-item__link__link__wrapper__main
                      .mypage-item__link__link__wrapper__main__figure
                        =image_tag product.product_images[0].image.url , class: "is-higher-width" 
                      .mypage-item-body
                        .mypage-item-text
                          = product.title
                        %div
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "heart")
                            %span
                              = product.likes.count
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "comment")
                            %span
                              = product.comments.count
                          - if  product.state == "completed"
                            .mypage-item-status.bold.blueblock
                              取引完了
                    .mypage-item__link__link__wrapper__icon
                      = icon("fas", "angle-right fa-2x")
      -else
        %li.notpresent
          %h3.gazou
            出品中の商品は現在ありません

app/views/users/_showedit_main.html.haml
%section.mypage-tab-container
  %h2.mypage-tab-head 出品した商品
  %ul.listing-tabs
    %li.listing-tabs__tab.tab_showedit
      %h3
        = link_to   showedit_user_path(current_user),         data:{toggle:"tab"} do
          出品中
    %li.listing-tabs__tab.tab_show_transaction
      %h3
        = link_to   show_transaction_user_path(current_user), data:{toggle:"tab"} do
          取引中
    %li.listing-tabs__tab.tab_show_completed
      %h3
        = link_to   show_completed_user_path(current_user),   data:{toggle:"tab"} do
          売却済み
  .tab-content
    %ul.mypage-item
      - if @products.present?
        -@products.each do | product |
          %li
            .mypage-item__link
              - if product.state == "in_sale" || product.state == "pending"
                = link_to showmain_product_path(product), class: "mypage-item__link__link"  do
                  .mypage-item__link__link__wrapper
                    .mypage-item__link__link__wrapper__main
                      .mypage-item__link__link__wrapper__main__figure
                        =image_tag product.product_images[0].image.url , class: "is-higher-width" 
                      .mypage-item-body
                        .mypage-item-text
                          = product.title
                        %div
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "heart")
                            %span
                              = product.likes.count
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "comment")
                            %span
                              = product.comments.count
                          - if product.state == "in_sale"
                            .mypage-item-status.bold.awaiting
                              出品中
                          - elsif  product.state == "pending"
                            .mypage-item-status.bold.pending
                              公開停止中
                          - elsif product.state == "waiting_for_shipping"
                            .mypage-item-status.bold.pending
                              発送待ち
                          - elsif product.state == "on_delivery"
                            .mypage-item-status.bold.awaiting
                              配達中
                          - elsif  product.state == "arrived"
                            .mypage-item-status.bold.pending
                              受取評価待ち
                    .mypage-item__link__link__wrapper__icon
                      = icon("fas", "angle-right fa-2x")
              - elsif product.state == "waiting_for_shipping" || product.state == "on_delivery" || product.state == "arrived"
                = link_to show_transaction_main_product_path(product), class: "mypage-item__link__link"  do
                  .mypage-item__link__link__wrapper
                    .mypage-item__link__link__wrapper__main
                      .mypage-item__link__link__wrapper__main__figure
                        =image_tag product.product_images[0].image.url , class: "is-higher-width" 
                      .mypage-item-body
                        .mypage-item-text
                          = product.title
                        %div
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "heart")
                            %span
                              = product.likes.count
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "comment")
                            %span
                              = product.comments.count
                          - if product.state == "waiting_for_shipping"
                            .mypage-item-status.bold.redblock
                              発送待ち
                          - elsif product.state == "on_delivery"
                            .mypage-item-status.bold.awaiting
                              配達中
                          - elsif  product.state == "arrived"
                            .mypage-item-status.bold.pending
                              完了処置待ち
                    .mypage-item__link__link__wrapper__icon
                      = icon("fas", "angle-right fa-2x")
              - elsif product.state == "completed"
                = link_to show_completed_main_product_path(product), class: "mypage-item__link__link"  do
                  .mypage-item__link__link__wrapper
                    .mypage-item__link__link__wrapper__main
                      .mypage-item__link__link__wrapper__main__figure
                        =image_tag product.product_images[0].image.url , class: "is-higher-width" 
                      .mypage-item-body
                        .mypage-item-text
                          = product.title
                        %div
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "heart")
                            %span
                              = product.likes.count
                          %span.listing-item-count
                            %i.icon
                              = icon("far", "comment")
                            %span
                              = product.comments.count
                          - if product.state == "completed"
                            .mypage-item-status.bold.awaiting
                              取引完了
                    .mypage-item__link__link__wrapper__icon
                      = icon("fas", "angle-right fa-2x")
      -else
        %li.notpresent
          %h3.gazou
            出品中の商品は現在ありません

app/views/users/_todo.html.haml
%section.mypage-tabs
  %ul.mypage-tabs__do
    %li
      %h3
        = link_to notification_user_path(current_user) , class: "oshirase-tag" , data:{toggle:"tab"} do
          お知らせ
    %li.active
      %h3
        = link_to todo_user_path(current_user) , class: "todo-tag" , data:{toggle:"tab"} do
          やることリスト
  %ul.mypage-item
    - if @todos
      - @todos.each do | todo |
        %li.mypage-item__list-info
          = link_to "", class:"mypage-item__list-info__link" do
            .mypage-item__list-info__link__mark
              = image_tag "https://www.mercari.com/jp/assets/img/common/common/logo-gray-icon.svg?39597161", class:"mark_m"
            .mypage-item__list-info__link__item-body
              .mypage-item__list-info__link__item-body__text
                TECHさんから「20歳の自分に受けさせたい文章講義」の取引メッセージがあります。返信をお願いします。
              %time.icon-left-time
                = icon("far", "clock icon-time fa-lg")
                %span 26 分前
            = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
        %li.mypage-item__list-info
          = link_to "", class:"mypage-item__list-info__link" do
            .mypage-item__list-info__link__mark
              = image_tag "https://www.mercari.com/jp/assets/img/common/common/logo-gray-icon.svg?39597161", class:"mark_m"
            .mypage-item__list-info__link__item-body
              .mypage-item__list-info__link__item-body__text
                EXPERTさんが「ダッフィーぬいぐるみ Sサイズ ディズニー 備品」を購入しました。。コンビニ/ATM払いを選択しています。支払いが済んだらやることリストに表示されます。
              %time.icon-left-time
                = icon("far", "clock icon-time fa-lg")
                %span 4 ヵ月前
            = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
    - else
      %li.mypage-item__list-info__not
        お知らせの商品がありません

app/views/users/card.html.haml
= render "layouts/header"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "card"
= render "layouts/footer"

app/views/users/index.html.haml
= render "layouts/header"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "users_main"
= render "layouts/footer"

app/views/users/like.html.haml
= render "layouts/header"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "like"
= render "layouts/footer"

app/views/users/notification.html.haml
= render "layouts/header"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "notification"
= render "layouts/footer"

app/views/users/purchase.html.haml
= render "layouts/header"
%nav.gretel
  - breadcrumb :purchase
  = breadcrumbs separator: "＞"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "purchase_main"
= render "layouts/footer"

app/views/users/purchased.html.haml
= render "layouts/header"
%nav.gretel
  - breadcrumb :purchased
  = breadcrumbs separator: "＞"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "purchase_main"
= render "layouts/footer"

app/views/users/show_completed.html.haml
= render "layouts/header"
%nav.gretel
  - breadcrumb :completed
  = breadcrumbs separator: "＞"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "showedit_main"
= render "layouts/footer"

app/views/users/showedit.html.haml
= render "layouts/header"
%nav.gretel
  - breadcrumb :showedit
  = breadcrumbs separator: "＞"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "showedit_main"
= render "layouts/footer"

app/views/users/todo.html.haml
= render "layouts/header"
= render "layouts/exhibit__btn"
%section.mypage-wrapper
  .left-content
    = render "layouts/sidebar"
  .right-content
    = render "todo"
= render "layouts/footer"