config/routes.rb
Rails.application.routes.draw do
  resources :card 
  get 'regulation/new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products , only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :likes,     only: [:create,:destroy]
    resources :comments,  only: [:new, :create]
    collection do
      get :sell
      get :select_category_m
      get :select_category_s
    end
    member do 
      get :showmain
      get :show_transaction_main
      get :show_completed_main
      get :purchase_transaction
      get :purchase_completed
      get :buy
      get :pay
      get :ship
      get :recieve
      get :pend
      get :resell
      get :close
    end

  end
  resources :users do
    member do
      get :plofile
      get :identification
      get :card
      get :logout
      get :notification
      get :todo
      get :like
      get :showedit
      get :show_transaction
      get :show_completed
      get :purchase
      get :purchased
    end
  end
  resources :trials, only: [:index,:create,:new, :edit, :update]
  resources :regulation do
    collection do
      get :singup1
      get :singup2
      get :singup3
      get :singup4
      get :singup5
    end
  end 
end  

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category 
  has_many :product_images, dependent: :destroy
  has_many :likes,          dependent: :delete_all
  has_many :comments,       dependent: :delete_all
  belongs_to :user
  belongs_to :buyer, class_name: "User", optional: true
  accepts_nested_attributes_for :product_images
  validates :title,:category_id,:shipping_charges,:shipping_area,:shipping_date,
            :shipping_method,:price,:size,:description,:condition,presence: true
  validates :price, numericality: { greater_than_or_equal_to: 300  }
  validates :price, numericality: { less_than_or_equal_to: 9999999 }
  enum condition:         ["新品、未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"]
  enum shipping_charges:  ["送料込み(出品者負担)","着払い(購入者負担)"]
  enum shipping_date:     ["1~2日で発送","2~3日で発送","4~7日で発送"]
  enum shipping_method:   ["未定","クロネコヤマト","ゆうパック","ゆうメール"]
  enum size:              ["XXS以下","XS(SS)","S","M","L","XL(LL)","2XL(3L)","3XL(4L)","4XL(5L)以上","FREE SIZE"]
  enum state:              { in_sale: 0, waiting_for_shipping: 1, on_delivery: 2, arrived: 3, completed: 10, pending: 99 }

  def state_transition(state)
    self.update(state: state)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only:[:edit, :update, :show, :pay, :buy, :destroy, :pend, :resell, :ship, :recieve, :close, :showmain, :show_transaction_main, :show_completed_main, :purchase_transaction, :purchase_completed]

  def index 
    @products = Product.order("id DESC").limit(10)
    category_ids_mens =Category.buildArray_of_family_from_parent(1)
    @products_mens = Product.where(category_id: category_ids_mens).order("id DESC").limit(10)
    category_ids_ladys =Category.buildArray_of_family_from_parent(61)
    @products_ladys = Product.where(category_id: category_ids_ladys).order("id DESC").limit(10)
    category_ids_kids =Category.buildArray_of_family_from_parent(134)
    @products_kids = Product.where(category_id: category_ids_kids).order("id DESC").limit(10)
  end
  def sell
    @product= Product.new()
    @parent = Category.where(ancestry: nil)
    @children = Category.none
    @grandchildren = Category.none
    @product.product_images.build
  end 

  def select_category_m
    parent = Category.find_by(id: params[:category_id1])
    @children = parent.children
    respond_to do |format|
      format.json
    end
  end
  def select_category_s
    child= Category.find_by(id: params[:category_id2])
    @grandchildren = child.children
    respond_to do |format|
      format.json
    end
  end

  def create
    @product = Product.new(product_params)
    if params[:image].present? && @product.save
      product_image_params[:images].each do |image|
        @product.product_images.build
        product_image = @product.product_images.new(image: image)
        product_image.save
      end
    end
    respond_to do |format|
      format.json
    end
  end

  def edit
    @grandchildren  = Category.where(id: @product.category_id)
    @children       = Category.where(id: @grandchildren[0].parent)
    @parent         = Category.where(ancestry: nil)
    @parent_current = Category.find_by(id: @children[0].parent.id)

    @product.product_images.build
    @product.product_images.each do |product_image|
      product_image.image.cache!
    end
  end

  def update
    if @product.update(product_params)
      @product_images = @product.product_images
      delete_product_image_ids = []
      if delete_product_image_params.present?
        delete_product_image_params[:delete_request_index].each do |index|
          delete_product_image_ids << @product_images[index.to_i].id
        end
        delete_product_image_ids.each do |id|
          product_image = @product_images.find(id)
          product_image.destroy
        end
      end
      if params[:image].present?
        product_image_params[:images].each do |image|
          @product_images.build
          product_image = @product_images.new(image: image)
          product_image.save
        end
      end
      
    end
    respond_to do |format|
      format.json
    end
  end

  def show
    @products_this_seller = @product.user.products.order('id DESC').where.not(id: params[:id]).limit(6)
    @category = @product.category
    @products_this_category = @category.products.order('id DESC').where.not(user_id:@product.user).limit(6)
    if user_signed_in? 
      @likes = @product.likes
      @like  = @likes.find_by(user_id: current_user.id)
    end  
    @comment = Comment.new()
  end

  def buy
    @address = current_user.address
    @card = Card.find_by(user_id: current_user.id)
    unless @card.blank?
      Payjp.api_key = ENV["CARD_SEECRET_KEY"]
      Payjp.read_timeout = 90
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end
  def pay
    card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = ENV["CARD_SEECRET_KEY"]
    Payjp.read_timeout = 90
    Payjp::Charge.create(
      amount: @product.price,     #支払金額
      customer: card.customer_id, #顧客ID
      currency: 'jpy',            #日本円
    )
    @product.update(buyer_id: current_user.id)
    @product.state_transition("waiting_for_shipping")
  end

  def showmain
    @products_this_seller = @product.user.products.order('id DESC').where.not(id: params[:id]).limit(6)
    @category = @product.category
    @products_this_category = @category.products.order('id DESC').where.not(user_id:@product.user).limit(6)
    @comment = Comment.new()
  end

  def destroy
    if @product.destroy
      redirect_to showedit_user_path(current_user)
    end
  end

  def pend
    @product.state_transition("pending")
    redirect_to showmain_product_path(@product)
  end

  def resell
    @product.state_transition("in_sale")
    redirect_to showmain_product_path(@product)
  end

  def ship
    @product.state_transition("on_delivery")
    redirect_to show_transaction_main_product_path(@product)
  end

  def recieve
    @product.state_transition("arrived")
    redirect_to purchase_transaction_product_path(@product)
  end

  def close
    @product.state_transition("completed")
    redirect_to show_completed_main_product_path(@product)
  end

  def show_transaction_main
  end

  def show_completed_main
  end

  def purchase_transaction
  end

  def purchase_completed
  end

  private

  def product_params
      params.require(:product).permit(:title, :description, :category_id, :size, :brand_id, :condition, :shipping_charges, :shipping_area, :shipping_method, :shipping_date, :price).merge(user_id:current_user.id)
  end

  def product_image_params
    params.require(:image).permit({images:[]})
  end

  def delete_product_image_params
    params.require(:product).permit({delete_request_index:[]})
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products_bland.html.haml
.top-main__contens__content
  %h2.top-main__contens__title
    人気のブランド
  %ul.top-main__contens__lists
    = link_to do
      %li.menu__list
        ナイキ
    = link_to do    
      %li.menu__list
        シャネル
    = link_to do    
      %li.menu__list     
        シュプリーム
    = link_to do    
      %li.menu__list
        プーマ
.top-main__contens__category
  .top-main__contens__category__menu
    .category__item
      .category__item__top
        .category__item__top__title
          hige新着アイテム
        = link_to do
          %h2.category__item__top__refe
            もっと見る＞
      .category__item__bottom.fadein
        - @products.each do |product|
          .category__item__bottom__product
            - if product.buyer
              .category__item__bottom__product__sold-label
                %p SOLD
            = link_to product_path(product) do
              %span.category__item__bottom__product__price
                = "¥#{product.price.to_s(:delimited)}"
              .category__item__bottom__product__photo
                = image_tag(product.product_images[0].image.url, class: "image3" )     
              %h3.category__item__bottom__product__text
                = product.title

app/views/products/show.html.haml
= render "layouts/header"
%section.item-box-container
  %h1.item-box-container__item-name
    = @product.title
  .item-box-container__main
    .item-box-container__main__photo
      .item-box-container__main__photo__inner
        .item-box-container__main__photo__inner__large-box
          - if @product.buyer
            .item-box-container__main__photo__inner__large-box__sold-label
              %p SOLD
          .item-box-container__main__photo__inner__large-box__wrapper
            - if @product 
              - @product.product_images.each do | product_image |
                .item-box-container__main__photo__inner__large-box__wrapper__item
                  .item-box-container__main__photo__inner__large-box__wrapper__item__inner
                    = image_tag product_image.image.url, class:"item-box-container__main__photo__inner__large-box__wrapper__item__inner__img"
        .item-box-container__main__photo__inner__nav
          .item-box-container__main__photo__inner__nav__prev
            prev
          .item-box-container__main__photo__inner__nav__next
            next
        .item-box-container__main__photo__inner__smal-box-wrapper
          - if @product 
            - @product.product_images.each_with_index do | product_image ,i|
              - if i==0
                .item-box-container__main__photo__inner__smal-box-wrapper__item.active{id: "image#{i}"}
                  %span
                  .item-box-container__main__photo__inner__smal-box-wrapper__item__inner
                    = image_tag product_image.image.url

              - else
                .item-box-container__main__photo__inner__smal-box-wrapper__item{id: "image#{i}"}
                  %span
                  .item-box-container__main__photo__inner__smal-box-wrapper__item__inner
                    = image_tag product_image.image.url
    .item-box-container__main__price-box
      %span.item-box-container__main__price-box__price 
        = "¥#{@product.price.to_s(:delimited)}"
      %span.item-box-container__main__price-box__tax (税込)
      %span.item-box-container__main__price-box__shipping-fee
        - if @product.shipping_charges_before_type_cast == 0
          送料込み
        - else
          着払い
    %table.item-box-container__main__detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to plofile_user_path(@product.user) ,class:"seller_link" do
              = @product.user.nickname
            %div
              .item-user-ratings
                %i.fas.fa-laugh.icon-laugh.evaluation-mark
                %span 0
              .item-user-ratings
                %i.fas.fa-meh.icon-meh.evaluation-mark
                %span 0
              .item-user-ratings
                %i.fas.fa-frown.icon-frown.evaluation-mark
                %span 0
        %tr
          %th カテゴリー
          %td
            = link_to "",class:"item_category_link" do
              %div
                = @category.parent.parent.name
            = link_to "",class:"item_category_link" do
              .item_sub-category_link
                = icon("fas", "angle-right fa-1g")
                = @category.parent.name
            = link_to "",class:"item_category_link" do
              .item_sub-category_link
                = icon("fas", "angle-right fa-1g")
                = @category.name
        %tr
          %th ブランド
          %td
            - if @product.brand_id
              = link_to "" do
                = @product.brand_id
        %tr
          %th 商品の状態
          %td
            = @product.condition
        %tr
          %th 配送料の負担
          %td 
            = @product.shipping_charges
        %tr
          %th 配送の方法
          %td
            = @product.shipping_method
        %tr
          %th 配送元地域
          %td
            = link_to "" do
              = Prefecture.find(@product.shipping_area).name
        %tr
          %th 発送日の目安
          %td
            = @product.shipping_date
  .item-box-container__price-box
    %span.item-box-container__price-box__price
      = "¥#{@product.price.to_s(:delimited)}"
    %span.item-box-container__price-box__tax (税込)
    %span.item-box-container__price-box__shipping-fee
      - if @product.shipping_charges_before_type_cast == 0
        送料込み
      - else
        着払い
  - if @product.buyer
    .item-buy-btn_sold
      売り切れました
  - else
    = link_to buy_product_path(@product), class:"item-buy-btn" do
      購入画面に進む
    = link_to "" , class:"item-action-text", data:{action:"item/openDetail",adjust:{url:""},key:"id=m81784685949",play:{id:"com.kouzoh.mercari" } } do
      アプリで購入
  .item-box-container__description
    %p.item-box-container__description__inner
      = @product.description
  .item-box-container__evaluation-btn
    .item-box-container__evaluation-btn__left
      %button.item-box-container__evaluation-btn__left__like.like_btn{data: { like: @like  } }
        .off-to-on{style:"display:none;"}
          .like_link
            = link_to product_likes_path(@product),  {method:"post", remote: true} do
              = icon("far", "heart icon-like-border fa-lg")
              %span いいね!
        .on-to-off{style:"display:none;"}
          .like_link
            = link_to product_like_path(@product), {method:"delete", remote: true} do
              = icon("fas", "heart icon-like-border fa-lg" )
              %span いいね!
        %span.fade-in-down{data:{num:"like"}}
          -if user_signed_in?
            = @likes.count
      = link_to "" , class:"item-button item-button-report", data: { modal:"report-item", open: "modal"} do
        = icon("far", "flag icon-flag fa-lg")
        %span 不適切な商品の報告
    .item-box-container__evaluation-btn__right
      = link_to ""  do
        = icon("fas", "lock icon-lock fa-lg")
        %span あんしん・あんぜんへの取り組み

.float-item-buy-btn
  .float-item-buy-btn__box
    - if @product.buyer
      .item-buy-btn_sold
        売り切れました
    - else
      = link_to buy_product_path(@product), class:"item-buy-btn" do
        購入画面に進む

.item-box-message
  .item-box-message__container
    .item-box-message__container__content
      %ul.item-box-message__container__content__list
        - if @product.comments
          - @product.comments.each do |comment|
            %li.item-box-message__container__content__list__message-box
              = link_to comment.user , class:"item-box-message__container__content__list__message-box__lunchar" do
                %figure.item-box-message__container__content__list__message-box__lunchar__box
                  %div.item-box-message__container__content__list__message-box__lunchar__box__avatar
                    = image_tag "//static.mercdn.net/thumb/members/810915501.jpg?1395785151"
                  .item-box-message__container__content__list__message-box__lunchar__box__name
                    = comment.user.nickname
                - if comment.user == @product.user 
                  .item-box-message__container__content__list__message-box__lunchar__role
                    出品者
              .item-box-message__container__content__list__message-box__body
                .item-box-message__container__content__list__message-box__body__text
                  = comment.body
                .item-box-message__container__content__list__message-box__body__wrapper
                  %time.item-box-message__container__content__list__message-box__body__wrapper__icon-left
                    = icon("far", "clock icon-time fa-lg")
                    %span
                      =comment.created_at.to_s
                  .item-box-message__container__content__list__message-box__body__wrapper__icon-right
                    = form_with url:"", method:"post" do |f|
                      .actions
                        = f.button  type: 'submit', class: 'btn-flag' do
                          = icon("far", "flag icon-flag fa-lg")
                  .item-box-message__container__content__list__message-box__body__balloon
    .item-box-message__container__notice
      - if @product.buyer
        .item-box-message__container__notice__form
          .item-box-message__container__notice__form__submit
            売り切れのためコメントできません
      - else
        = form_for [@product,@comment] ,method: :post, html: {class: "item-box-message__container__notice__form"} do |f|
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = f.text_area :body , class:"textarea-default"
          = f.submit value:"コメントする", class:"item-box-message__container__notice__form__submit"
    %aside.item-box-message__container__modal
      .item-box-message__container__modal__banner
        .item-box-message__container__modal__banner__body
          .item-box-message__container__modal__banner__body__head 確認
          %div{"data-comment" => "body"}
          %br/
          本当にこのコメントを削除してよろしいですか？
        = form_with url:"", class:"item-box-message__container__modal__banner__form" do |f|
          .item-box-message__container__modal__banner__form__wrapper
            .item-box-message__container__modal__banner__form__wrapper__btn-block
            .item-box-message__container__modal__banner__form__wrapper__btn-cancel{data:{close: "modal"} }キャンセル
            %button.modal-btn.modal-btn-submit{type: "submit"}
              削除する

%ul.link-item-prev-next
  %li.nav-item-link-prev
    -if  Product.where(id: @product.id + 1).present?
      = link_to product_path(Product.where(id: @product.id + 1)[0]) do
        = icon("fas", "chevron-left angle-left fa-lg")
        %p
          = Product.where(id: @product.id + 1)[0].title
  %li.link-item-next
    -if  Product.where(id: @product.id - 1).present?
      = link_to product_path(Product.where(id: @product.id - 1)[0]) do
        %p
          = Product.where(id: @product.id - 1)[0].title
        = icon("fas", "chevron-right angle-right fa-lg")
        
.ssn-block
  .ssn-block__inner
    = link_to "", class:"ssn-block__inner__item facebook" do
      = icon("fab", "facebook-square icon-facebook fa-3x")
    = link_to "", class:"ssn-block__inner__item twitter" do
      = icon("fab", "twitter-square icon-twitter fa-3x")
    = link_to "", class:"ssn-block__inner__item pinterest" do
      = icon("fab", "pinterest-square icon-pinterest fa-3x")

- if @products_this_seller
  .related-item-box
    .related-item-box__inner
      %h2.related-item-box__inner__head
        = link_to "" do
          = "#{@product.user.nickname}さんのその他の出品"
      .related-item-box__inner__wrapper
        - @products_this_seller.each do |product|
          .related-item-box__inner__wrapper__items-box
            - if product.buyer
              .related-item-box__inner__wrapper__items-box__sold-label
                %p SOLD
            = link_to  product_path(product) do
              .related-item-box__inner__wrapper__items-box__photo
                - if product.product_images[0]
                  = image_tag product.product_images[0].image.url
              .related-item-box__inner__wrapper__items-box__price-label
                = "¥#{product.price.to_s(:delimited)}"
              .related-item-box__inner__wrapper__items-box__body
                %h3.related-item-box__inner__wrapper__items-box__body__name
                  = product.title
                .related-item-box__inner__wrapper__items-box__body__num
                  .related-item-box__inner__wrapper__items-box__body__num__price
                    = "¥#{product.price.to_s(:delimited)}"
                  .related-item-box__inner__wrapper__items-box__body__num__like
                    = icon("far", "heart icon-heart fa-lg")
                    %span.num
                      = product.likes.count
- if @products_this_category
  .related-item-box
    .related-item-box__inner
      %h2.related-item-box__inner__head
        = link_to "" do
          = "#{@product.category.name} その他の出品"
      .related-item-box__inner__wrapper
        - @products_this_category.each do |product|
          .related-item-box__inner__wrapper__items-box
            - if product.buyer
              .related-item-box__inner__wrapper__items-box__sold-label
                %p SOLD
            = link_to product_path(product) do
              .related-item-box__inner__wrapper__items-box__photo
                = image_tag product.product_images[0].image.url if product.product_images[0]
              .related-item-box__inner__wrapper__items-box__price-label
                = product.title
              .related-item-box__inner__wrapper__items-box__body
                %h3.related-item-box__inner__wrapper__items-box__body__name
                  = product.title
                .related-item-box__inner__wrapper__items-box__body__num
                  .related-item-box__inner__wrapper__items-box__body__num__price
                    = "¥#{product.price.to_s(:delimited)}"
                  .related-item-box__inner__wrapper__items-box__body__num__like
                    = icon("far", "heart icon-heart fa-lg")
                    %span.num
                      = product.likes.count
%nav.bread-crumbs-products-show
  %ul
    %li{itemscope:"", itemtype: ""}
      = link_to root_path do
        %span{itemprop: "title"} メルカリ
      = icon("fas", "angle-right fa-lg")
    %li{itemscope: "", itemtype: ""}
      %span{itemprop: "title"}
        = @product.title
= render "layouts/footer"

app/views/products/showmain.html.haml
= render "layouts/header"
%section.item-box-container
  %h1.item-box-container__item-name
    = @product.title
  .item-box-container__main
    .item-box-container__main__photo
      .item-box-container__main__photo__inner
        .item-box-container__main__photo__inner__large-box
          - if @product.state == "pending"
            .item-box-container__main__photo__inner__large-box__pending-label
              %p 公開停止中
          - elsif @product.buyer
            .item-box-container__main__photo__inner__large-box__sold-label
              %p SOLD
          .item-box-container__main__photo__inner__large-box__wrapper
            - if @product 
              - @product.product_images.each do | product_image |
                .item-box-container__main__photo__inner__large-box__wrapper__item
                  .item-box-container__main__photo__inner__large-box__wrapper__item__inner
                    = image_tag product_image.image.url, class:"item-box-container__main__photo__inner__large-box__wrapper__item__inner__img"
        .item-box-container__main__photo__inner__nav
          .item-box-container__main__photo__inner__nav__prev
            prev
          .item-box-container__main__photo__inner__nav__next
            next
        .item-box-container__main__photo__inner__smal-box-wrapper
          - if @product 
            - @product.product_images.each_with_index do | product_image ,i|
              - if i==0
                .item-box-container__main__photo__inner__smal-box-wrapper__item.active{id: "image#{i}"}
                  %span
                  .item-box-container__main__photo__inner__smal-box-wrapper__item__inner
                    = image_tag product_image.image.url
              - else
                .item-box-container__main__photo__inner__smal-box-wrapper__item{id: "image#{i}"}
                  %span
                  .item-box-container__main__photo__inner__smal-box-wrapper__item__inner
                    = image_tag product_image.image.url
    .item-box-container__main__price-box
      %span.item-box-container__main__price-box__price 
        = "¥#{@product.price.to_s(:delimited)}"
      %span.item-box-container__main__price-box__tax (税込)
      %span.item-box-container__main__price-box__shipping-fee 送料込み
    %table.item-box-container__main__detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to plofile_user_path(@product.user) ,class:"seller_link" do
              = @product.user.nickname
            %div
              .item-user-ratings
                %i.fas.fa-laugh.icon-laugh.evaluation-mark
                %span 0
              .item-user-ratings
                %i.fas.fa-meh.icon-meh.evaluation-mark
                %span 0
              .item-user-ratings
                %i.fas.fa-frown.icon-frown.evaluation-mark
                %span 0
        %tr
          %th カテゴリー
          %td
            = link_to "",class:"item_category_link" do
              %div
                = @category.parent.parent.name
            = link_to "",class:"item_category_link" do
              .item_sub-category_link
                = icon("fas", "angle-right fa-1g")
                = @category.parent.name
            = link_to "",class:"item_category_link" do
              .item_sub-category_link
                = icon("fas", "angle-right fa-1g")
                = @category.name
        %tr
          %th ブランド
          %td
            - if @product.brand_id
              = link_to "" do
                = @product.brand_id
        %tr
          %th 商品の状態
          %td
            = @product.condition
        %tr
          %th 配送料の負担
          %td 
            = @product.shipping_charges
        %tr
          %th 配送の方法
          %td
            = @product.shipping_method
        %tr
          %th 配送元地域
          %td
            = link_to "" do
              = Prefecture.find(@product.shipping_area).name
        %tr
          %th 発送日の目安
          %td
            = @product.shipping_date
  .item-box-container__price-box
    %span.item-box-container__price-box__price
      = "¥#{@product.price.to_s(:delimited)}"
    %span.item-box-container__price-box__tax (税込)
    %span.item-box-container__price-box__shipping-fee
      - if @product.shipping_charges_before_type_cast == 0
        送料込み
      - else
        着払い
.item-box-message
  .listing-item-change-box
  %a.btn-default.btn-red
  = link_to edit_product_path(@product) ,class: "btn-default btn-red"do
    商品の編集
  %p.text-center or
  -if @product.state == "in_sale" 
    %button.btn-default.btn-gray
      = link_to "出品を一旦停止する",pend_product_path(@product)
  -elsif @product.state == "pending"
    %button.btn-default.btn-red
      = link_to "出品を再開する",resell_product_path(@product)   
  %button#modal-open-btn.btn-gray
    = link_to "この商品を削除する", ""


#overlay.hidden
  #modalWindow
    .modal-message-box
      %div 確認
      %div 本当に削除しますか？
    #modal-close-btn キャンセル
    #delete-comformation-btn
      = link_to "削除する",product_path(@product), method: :DELETE 

.item-box-message
  .item-box-message__container
    .item-box-message__container__content
      %ul.item-box-message__container__content__list
        - if @product.comments
          - @product.comments.each do |comment|
            %li.item-box-message__container__content__list__message-box
              = link_to comment.user , class:"item-box-message__container__content__list__message-box__lunchar" do
                %figure.item-box-message__container__content__list__message-box__lunchar__box
                  %div.item-box-message__container__content__list__message-box__lunchar__box__avatar
                    = image_tag "//static.mercdn.net/thumb/members/810915501.jpg?1395785151"
                  .item-box-message__container__content__list__message-box__lunchar__box__name
                    = comment.user.nickname
                - if comment.user == @product.user 
                  .item-box-message__container__content__list__message-box__lunchar__role
                    出品者
              .item-box-message__container__content__list__message-box__body
                .item-box-message__container__content__list__message-box__body__text
                  = comment.body
                .item-box-message__container__content__list__message-box__body__wrapper
                  %time.item-box-message__container__content__list__message-box__body__wrapper__icon-left
                    = icon("far", "clock icon-time fa-lg")
                    %span
                      =comment.created_at.to_s
                  .item-box-message__container__content__list__message-box__body__wrapper__icon-right
                    = form_with url:"", method:"post" do |f|
                      .actions
                        = f.button  type: 'submit', class: 'btn-flag' do
                          = icon("far", "flag icon-flag fa-lg")
                  .item-box-message__container__content__list__message-box__body__balloon
    .message__container              
      .item-box-message__container__notice
        = form_for [@product,@comment] ,method: :post, html: {class: "item-box-message__container__notice__form"} do |f|
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = f.text_area :body , class:"textarea-default"
          = f.submit value:"コメントする", class:"item-box-message__container__notice__form__submit"
      %aside.item-box-message__container__modal
        .item-box-message__container__modal__banner
          .item-box-message__container__modal__banner__body
            .item-box-message__container__modal__banner__body__head 確認
            %div{"data-comment" => "body"}
            %br/
            本当にこのコメントを削除してよろしいですか？
          = form_with url:"", class:"item-box-message__container__modal__banner__form" do |f|
            .item-box-message__container__modal__banner__form__wrapper
              .item-box-message__container__modal__banner__form__wrapper__btn-block
              .item-box-message__container__modal__banner__form__wrapper__btn-cancel{data:{close: "modal"} }キャンセル
              %button.modal-btn.modal-btn-submit{type: "submit"}
                削除する
%ul.link-item-prev-next
  %li.nav-item-link-prev
    -if  Product.where(id: @product.id + 1).present?
      = link_to product_path(Product.where(id: @product.id + 1)[0]) do
        = icon("fas", "chevron-left angle-left fa-lg")
        %p
          = Product.where(id: @product.id + 1)[0].title
  %li.link-item-next
    -if  Product.where(id: @product.id - 1).present?
      = link_to product_path(Product.where(id: @product.id - 1)[0]) do
        %p
          = Product.where(id: @product.id - 1)[0].title
        = icon("fas", "chevron-right angle-right fa-lg")
= render "layouts/footer"