config/routes.rb
Rails.application.routes.draw do
  resources :card 
  get 'regulation/new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products , only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :likes,     only: [:create,:destroy]
    resources :comments,  only: [:new, :create]
    collection do
      get :sell
      get :select_category_m
      get :select_category_s
    end
    member do 
      get :showmain
      get :show_transaction_main
      get :show_completed_main
      get :purchase_transaction
      get :purchase_completed
      get :buy
      get :pay
      get :ship
      get :recieve
      get :pend
      get :resell
      get :close
    end

  end
  resources :users do
    member do
      get :plofile
      get :identification
      get :card
      get :logout
      get :notification
      get :todo
      get :like
      get :showedit
      get :show_transaction
      get :show_completed
      get :purchase
      get :purchased
    end
  end
  resources :trials, only: [:index,:create,:new, :edit, :update]
  resources :regulation do
    collection do
      get :singup1
      get :singup2
      get :singup3
      get :singup4
      get :singup5
    end
  end 
end  

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  delegate :name, to: :prefectures
  belongs_to :user, optional: true

  #address情報入力のバリデーション
  # 空の値はゆるさない
  validates :post_num, :prefectures, :municipalities, :block_number ,presence: true
  # 郵便番号
  validates :post_num, format: { with: /\A[0-9]+\z/ }
  validates :post_num, length: { is: 7 } 
  # 半角数値以外許さない
  if :phone_number.empty?
    validates :phone_number, format: { with: /\A[0-9]+\z/ }
  end 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry 

  def self.buildArray_of_family_from_parent(parent_id)
    parent_ids          = Category.where(id: parent_id).ids
    children_ids        = Category.find(parent_id).children.ids.flatten
    grand_children_ids  = Category.find(parent_id).children.map{|child| child.children.ids}.flatten
    return parent_ids.push(children_ids).push(grand_children_ids).flatten!
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/pay.rb
class Pay < ApplicationRecord
  belongs_to :user, optional: true

  # pay情報入力のバリデーション
  # 空の値はゆるさない
  validates :card_id, :year, :month, :security_number ,presence: true
  # 半角数値制限
  validates :card_id, :year, :month, :security_number, format: { with: /\A[0-9]+\z/ }
  # 字数制限
  validates :card_id, length: { maximum: 10 }
  validates :year, :month, length: { maximum: 2 }
  validates :security_number, length: { maximum: 4 }
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/prodoct.rb
class Prodoct < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category 
  has_many :product_images, dependent: :destroy
  has_many :likes,          dependent: :delete_all
  has_many :comments,       dependent: :delete_all
  belongs_to :user
  belongs_to :buyer, class_name: "User", optional: true
  accepts_nested_attributes_for :product_images
  validates :title,:category_id,:shipping_charges,:shipping_area,:shipping_date,
            :shipping_method,:price,:size,:description,:condition,presence: true
  validates :price, numericality: { greater_than_or_equal_to: 300  }
  validates :price, numericality: { less_than_or_equal_to: 9999999 }
  enum condition:         ["新品、未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"]
  enum shipping_charges:  ["送料込み(出品者負担)","着払い(購入者負担)"]
  enum shipping_date:     ["1~2日で発送","2~3日で発送","4~7日で発送"]
  enum shipping_method:   ["未定","クロネコヤマト","ゆうパック","ゆうメール"]
  enum size:              ["XXS以下","XS(SS)","S","M","L","XL(LL)","2XL(3L)","3XL(4L)","4XL(5L)以上","FREE SIZE"]
  enum state:              { in_sale: 0, waiting_for_shipping: 1, on_delivery: 2, arrived: 3, completed: 10, pending: 99 }

  def state_transition(state)
    self.update(state: state)
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/trial.rb
class Trial < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :likes, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_one :address
  accepts_nested_attributes_for :address 
  has_many :cards
  has_one :pay
  accepts_nested_attributes_for :pay

  has_many :buyed_products,                                         foreign_key: "buyer_id", class_name: "Product"
  has_many :selling_products,  -> { where("buyer_id is NULL") },    foreign_key: "user_id", class_name: "Product"
  has_many :sold_products,     -> { where("buyer_id is not NULL")}, foreign_key: "user_id", class_name: "Product"
  
  # user情報入力バリデーション
    # 値が空ではない
      validates :nickname, :email, :password, :password_confirmation, :family_name, :first_name,
                :family_name_kana, :first_name_kana, :birthday_year, :birthday_month, :birthday_day, presence: true
      validates :password, confirmation: true
    # 苗字、名前は全角のカタ、ひら、漢字のどれかである
      validates :family_name, format:{ with: /\A[ぁ-んァ-ン一-龥]/ }
      validates :first_name, format:{ with: /\A[ぁ-んァ-ン一-龥]/ }
    # フリガナは全角カタカナである
      validates :family_name_kana, format:{ with: /\A[ァ-ヶー－]+\z/ }
      validates :first_name_kana, format:{ with: /\A[ァ-ヶー－]+\z/ }
    # 数値範囲指定  
      validates :birthday_year, numericality:{ greater_than_or_equal_to: 1930 }
      validates :birthday_year, numericality:{ less_than_or_equal_to: 2018 }
      validates :birthday_month, numericality:{greater_than_or_equal_to: 1 }
      validates :birthday_month, numericality:{less_than_or_equal_to: 12 }
      validates :birthday_day, numericality:{greater_than_or_equal_to: 1 }
      validates :birthday_day, numericality:{less_than_or_equal_to: 31 }     
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_exhibit__btn.html.haml
-# 出品ボタンーーーーーーーーーーー
.exhibit__btn
  =link_to sell_products_path do
    .exhibit__btn__content
      .exhibit__btn__content_text
        出品
      .exhibit__btn__content_image
        = icon("fas", "camera")

app/views/layouts/_footer.html.haml
.app-banner
  .app-banner__pc
    .app-banner__pc__inner
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner__pc__inner__clearfix
        %figure
          =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?2296184308",width: "68px"
        %ul.clearfix
          %li
            =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2296184308", width: "133"
          %li
            =link_to "#", target:"_blank" do
              =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2296184308", height: "40", width:"133"
    %figure
      =image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?2296184308",width:"300", height:"260"
.footer
  .footer__top
    .footer__list
      %h2.footer__list__title メルカリについて
      %ul
        %li.footer__top__list__text
          = link_to"会社概要（運営会社)"
        %li.footer__top__list__text
          = link_to"採用情報" 
        %li.footer__top__list__text
          = link_to"プレスリリース"
        %li.footer__top__list__text
          = link_to"公式ブログ" 
        %li.footer__top__list__text
          = link_to"メルカリロゴ利用ガイドライン" 
        %li.footer__link
          = link_to"https://twitter.com/mercari_jp" do
            = icon("fab", "twitter")
        %li.footer__link
          = link_to "https://www.facebook.com/mercarijp" do
            = icon("fab", "facebook")
    .footer__list
      %h2.footer__list__title ヘルプ＆ガイド
      %ul
        %li.footer__cell__list__text
          = link_to"メルカリガイド" 
        %li.footer__cell__list__text
          = link_to"らくらくメルカリ便" 
        %li.footer__cell__list__text
          = link_to"ゆうゆうメルカリ便" 
        %li.footer__cell__list__text
          = link_to"大型メルカリ便" 
        %li.footer__cell__list__text
          = link_to"車体取引ガイド"  
        %li.footer__cell__list__text
          = link_to"メルカリあんしん・あんぜん宣言！"  
        %li.footer__cell__list__text
          = link_to"偽ブランド品撲滅への取り組み" 
        %li.footer__cell__list__text
          = link_to"メルカリボックス"  
    .footer__list
      %h2.footer__list__title プライバシーと利用規約
      .footer__list
        %ul
          %li.footer__cell__list__text
            = link_to"プライバシーポリシー" 
          %li.footer__cell__list__text
            = link_to"メルカリ利用規約" 
          %li.footer__cell__list__text
            = link_to"あんしんスマホサポート制度に関する利用特約" 
          %li.footer__cell__list__text
            = link_to"コンプライアンスポリシー" 
          %li.footer__cell__list__text
            = link_to"個人データの安全管理に係る基本方針"  
          %li.footer__cell__list__text
            = link_to"特定商取引に関する表記" 
          %li.footer__cell__list__text
            = link_to"資金決済法に基づく表示" 
          %li.footer__cell__list__text
            = link_to"法令順守と犯罪抑止のために" 
    .footer__list
      %h2.footer__list__title 国
      %ul
        %li.footer__cell__list__text
          = link_to"日本" ,class: "footer-link" 
        %li.footer__cell__list__text
          = link_to"United States" ,class: "footer-link"
  .footer-bottom
    %a.footer-logo
      =image_tag"//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?2296184308",alt: "mercari", height:"33", width:"124"
    %span.footer-bottom__copyright
      %small © 2019 Mercari

app/views/layouts/_header.haml
.header
  .header__contents
    .header__contents__top
      .header__contents__top__log
        = link_to do 
          %img{width: "134", src: "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"}
      .form
        %input#box1{placeholder: "何かお探しですか？", type: "text"}
        %button#button1{type: 'submit'}
          = link_to do
            = fa_icon 'search'         
    .header__contents__bottom
      .header__contents__bottom__left
        .left__content
          = link_to do
            .left__content__bar  
            = fa_icon  "bars", class: 'tag'
            カテゴリーから探す
        .right__content
          = link_to do
            .left__content__tag
            = fa_icon  "tag", class: 'tag'
            ブランドから探す
      %ul.raight__menu
        %li.right__menu__list.heart
          = link_to do
            = fa_icon  "heart-o"
            いいね！一覧
        %li.right__menu__list.bell
          = link_to do
            = fa_icon  "bell-o"
            お知らせ
        %li.right__menu__list.bell
          = link_to do
            = fa_icon  "check"
            やることリスト
        %li.right__menu__list.user
          = link_to do
            = fa_icon  "user-o"
            マイページ
-# 出品ボタンーーーーーーーーーーー
.exhibit__btn
  = link_to do
    .exhibit__btn__content
      .exhibit__btn__content_text
        出品
      .exhibit__btn__content_image
        = fa_icon  "camera"

app/views/layouts/_header.html.haml
.header
  .header__contents
    .header__contents__top
      .header__contents__top__log
        = link_to root_path do
          %img{width: "134", src: "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg"}
      .form
        %input#box1{placeholder: "何かお探しですか？", type: "text"}
        %button#button1{type: 'submit'}
          = link_to do
            = icon("fas", "search")
    .header__contents__bottom
      .header__contents__bottom__left
        .left__content
          = link_to do
            .left__content__bar  
            = icon("fas", "bars tag")
            カテゴリーから探す
        .right__content
          = link_to do
            .left__content__tag
            = icon("fas", "tag tag")
            ブランドから探す 
      -if user_signed_in?        
        %ul.right__menu
          %li.right__menu__list.heart
            = link_to like_user_path(current_user) do
              = icon("far", "heart")
              いいね！一覧
          %li.right__menu__list.bell
            = link_to notification_user_path(current_user) do
              = icon("far", "bell")
              お知らせ
          %li.right__menu__list.bell
            = link_to todo_user_path(current_user) do
              = icon("fas", "check")
              やることリスト
          %li.right__menu__list.user
            = link_to user_path(current_user) do
              = icon("far", "user")
              マイページ
            .right__menu__list__hover-box
              .right__menu__list__hover-box__user-box
                .name
                  = "#{current_user.nickname} さん"
              %ul.right__menu__list__hover-box__mypage-nav__list  
                %li.right__menu__list__hover-box__mypage-nav__list__inner
                  =link_to like_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-like" do
                    いいね！一覧
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")
                %li.right__menu__list__hover-box__mypage-nav__list__inner
                  =link_to showedit_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-listings-listing" do
                    出品した商品 - 出品中
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")
                %li.right__menu__list__hover-box__mypage-nav__list__inner
                  =link_to show_transaction_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-listings-inprogress" do
                    出品した商品 - 取引中
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")
                %li.right__menu__list__hover-box__mypage-nav__list__inner
                  =link_to show_completed_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-listings-complete" do
                    出品した商品 - 売却済み
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")
                %li.right__menu__list__hover-box__mypage-nav__list__inner
                  =link_to purchase_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-purchase" do
                    購入した商品 - 取引中
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")
                %li.right__menu__list__hover-box__mypage-nav__list__inner
                  =link_to purchased_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-purchased" do
                    購入した商品 - 過去の取引
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")
                %li.side-box__mypage-nav__list__inner
                  =link_to logout_user_path(current_user), class:"right__menu__list__hover-box__mypage-nav__list__inner__item side-logout" do
                    ログアウト
                    = icon("fas", "angle-right right__menu__list__hover-box__mypage-nav__list__inner__item__icon fa-1g")


      -else        
        .right__menu__nave
          .right__menu__nave__left
            = link_to regulation_index_path, class: "right__menu__nave__left__text" do
              新規会員登録
          .right__menu__nave__right
            = link_to new_user_session_path, class: "right__menu__nave__right__text" do
              ログイン             

app/views/layouts/_sidebar.html.haml
.side-box
  %nav.side-box__mypage-nav
    %ul.side-box__mypage-nav__list
      %li.side-box__mypage-nav__list__inner
        =link_to user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-mypage" do
          マイページ
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to notification_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-notification" do
          お知らせ
          %span.mypage-nav-number
            -# お知らせ数をここに入れる
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to todo_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-todo" do
          やることリスト
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to like_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-like" do
          いいね！一覧
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to sell_products_path, class:"side-box__mypage-nav__list__inner__item side-sell" do
          出品する
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to showedit_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-listings-listing" do
          出品した商品 - 出品中
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to show_transaction_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-listings-inprogress" do
          出品した商品 - 取引中
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to show_completed_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-listings-complete" do
          出品した商品 - 売却済み
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to purchase_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-purchase" do
          購入した商品 - 取引中
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to purchased_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-purchased" do
          購入した商品 - 過去の取引
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-news" do
          ニュース一覧
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-review-history" do
          評価一覧
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-help-senter" do
          ガイド
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-suppoert" do
          お問い合わせ
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
    %h3.side-box__mypage-nav__head メルペイ
    %ul.side-box__mypage-nav__list
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-sales" do
          売上・振込申請
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-point" do
          ポイント
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
    %h3.side-box__mypage-nav__head 設定
    %ul.side-box__mypage-nav__list
      %li.side-box__mypage-nav__list__inner
        =link_to plofile_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-profile" do
          プロフィール
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-deliver_address" do
          発送元・お届け先住所変更
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to card_index_path, class:"side-box__mypage-nav__list__inner__item side-card" do
          支払い方法
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-email_password" do
          メール/パスワード
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to identification_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-identification" do
          本人情報
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to "", class:"side-box__mypage-nav__list__inner__item side-sms_confirmation" do
          電話番号の確認
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")
      %li.side-box__mypage-nav__list__inner
        =link_to logout_user_path(current_user), class:"side-box__mypage-nav__list__inner__item side-logout" do
          ログアウト
          = icon("fas", "angle-right side-box__mypage-nav__list__inner__item__icon fa-1g")

app/views/layouts/_single-footer.html.haml
%footer.single-footer
  %nav.single-footer__nav
    %ul.single-footer__nav__list
      %li.single-footer__nav__list__item
        = link_to "プライバシーポリシー","", class:"single-footer__nav__list__item__link"
      %li.single-footer__nav__list__item
        = link_to "メルカリ利用規約","", class:"single-footer__nav__list__item__link"
      %li.single-footer__nav__list__item
        = link_to "特定商取引に関する表記","", class:"single-footer__nav__list__item__link"
  = link_to root_path ,class:"single-footer__logo" do
    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3466462615"
  %p.single-footer__copyright
    %small © 2019 Mercari

app/views/layouts/_single-header.html.haml
%header.single-header
  %div.single-header__block
    = link_to root_path do
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3466462615", class:"single-header__block__img"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content:"text/html; charset=UTF-8", http: { equiv: "Content-Type" }, name:"viewport" , content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"  }
    %title FreemarketSample60bNagpya
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href:"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel:"stylesheet", type:"text/css"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
    %script{src: "https://www.google.com/recaptcha/api.js", type: "text/javascript"}
  %body
    = yield
 